name: conways

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
    networks:
      - default
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/data/db
      - mongodbconfig:/data/configdb

  conways.service:
    image: conways.service:0.1.0
    container_name: conways.service
    environment:
      MongoDbSettings__ConnectionString: mongodb://mongo:27017/
      MongoDbSettings__DatabaseName: ConwaysGameOfLife
      CorsSettings__AllowedOrigins: http://localhost:3000
    networks:
      - default
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - mongo

  conways.client:
    image: conways.client:0.1.0
    container_name: conways.client
    networks:
      - default
    ports:
      - "3000:3000"
    restart: on-failure

volumes:
  mongodbdata:
    name: mongodbdata
    external: true
  mongodbconfig:
    name: mongodbconfig
    external: true

networks:
  default:
    driver: bridge